### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by anchikpvl** [sulik76/ZabbixCUCMResourcesMonitoring#1]
I did everything according to the instructions, but I get such an error. Can you tell me how to fix it pls?

Cannot perform request: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol

**Comment by sulik76** [comment]
Hello @anchikpvl

This error indicates a problem with TLS protocol negotiation by curl which Zabbix uses to connect to the API. See this solution [https://stackoverflow.com/questions/70042160/get-request-ssl-choose-client-versionunsupported-protocol](https://stackoverflow.com/questions/70042160/get-request-ssl-choose-client-versionunsupported-protocol)
Try making connections from Zabbix server or Zabbix Proxy to CUCM using curl as in the article above and see what the result will be.
